### ISSUE TITLE
Adding sal.js to Scroll Animation libraries

### ISSUE THREAD

**Issue by mciastek** [sergey-pimenov/web-animation#4]
Hi, I really like your list of animation tools and libraries. I'm a creator of [sal.js](https://github.com/mciastek/sal) library, which helps with animating elements on scroll. Would mind adding my library to your list? I can prepare proper Pull Request if that suits you.

Best regards!

**Comment by sergey-pimenov** [comment]
Hi, Mirosław
You can add your tool using **[this](https://github.com/sergey-pimenov/web-animation/blob/master/CONTRIBUTING.md)** instruction.
Don't forget load logo of tool and add total size of your solution (JS + CSS + etc.)
